const MAXPLAYERS = 6;
const MINPLAYERS = 3;
const MAXLABELLENGTH = 25;
const MAXPLAYERNAMELENGTH = 10;

module.exports = { 
    MAXPLAYERS,
    MINPLAYERS,
    MAXLABELLENGTH,
    MAXPLAYERNAMELENGTH,
};